[package]
name = "tarea"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "solucion_1"
path = "solucion_1/main.rs"


[[bin]]
name = "solucion_2"
path = "solucion_2/main.rs"


[dependencies]
std-semaphore = "0.1"