[package]
name = "scope_crossbeam"
version = "0.1.0"
authors = ["pablodeymo <pablo@deymonnaz.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.0"
